---
- name: remove old version
  become: yes
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest

- name: Add Docker’s official GPG key
  become: yes
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Set up the stable repository
  become: yes
  shell:
    cmd: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Upgrade packages
  become: yes
  apt:
    upgrade: full

- name: Install Docker
  become: yes
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
