version: "3.1"
services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    container_name: rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
