version: "3.1"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: eil
      MONGO_INITDB_ROOT_PASSWORD: 123456!
    volumes:
      - /data/mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: eil
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456!
      ME_CONFIG_BASICAUTH_USERNAME: eil
      ME_CONFIG_BASICAUTH_PASSWORD: 123456!
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
