version: "3.1"
services:
  redis:
    image: "redis:5-alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
      - $PWD/redis.conf:/etc/redis/redis.conf:ro

    command: redis-server /etc/redis/redis.conf
